"""create folders table and add parent_id, workspace_id, desc

Revision ID: fcfd702cfa79
Revises: a5c89b93aec6
Create Date: 2025-08-13 08:39:02.016402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfd702cfa79'
down_revision: Union[str, None] = 'a5c89b93aec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
